name: 琞芃4082

on:
  schedule:
    - cron: '43 16 * * *'

jobs:
  hjd-user:
    name: 琞芃4082
    uses: ./.github/workflows/reusable-hjd-login.yaml
    with:
      forum_username: 琞芃4082
      user_index: '20'
    secrets: inherit