name: 玚翀5911

on:
  schedule:
    - cron: '23 16 * * *'

jobs:
  hjd-user:
    name: 玚翀5911
    uses: ./.github/workflows/reusable-hjd-login.yaml
    with:
      forum_username: 玚翀5911
      user_index: '16'
    secrets: inherit