name: 霂琤5701

on:
  schedule:
    - cron: '58 16 * * *'

jobs:
  hjd-user:
    name: 霂琤5701
    uses: ./.github/workflows/reusable-hjd-login.yaml
    with:
      forum_username: 霂琤5701
      user_index: '23'
    secrets: inherit