name: 神树通天

on:
  schedule:
    - cron: '30 16 * * *'

jobs:
  hjd-user:
    name: 神树通天
    uses: ./.github/workflows/reusable-hjd-login.yaml
    with:
      forum_username: 神树通天
      user_index: '7'
    secrets: inherit