name: Daily Job
on:
  schedule:
    # Run this workflow "At xx:30 UTC every day"
    - cron: '10 16 * * *'
  push:

jobs:
  daily-hjd:
    name: daily hjd
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        name: [ 南方风风, 臭屁鸡蛋, 叮叮咚呛, 皮蛋肥肉, 八角铃铛, 火炮千斤, 万灵伏威, 诗与江南, 福禄兄弟, 淬星耀世, 神树通天, 王者之锤 ]
    steps:
      - name: install chromium
        run: |
          sudo apt-get update
          sudo apt-get install -y chromium-browser
          sudo snap install chromium
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: hjd
          fetch-depth: 0
      - name: 关键 Run auto login
        env:
          FORUM_PASSWORD: ${{ secrets.FORUM_PASSWORD }}
          SECURITY_QUESTION: ${{ secrets.SECURITY_QUESTION }}
          SECURITY_ANSWER: ${{ secrets.SECURITY_ANSWER }}
          CHROME_PATH: ${{ secrets.CHROME_PATH }}
        run: |
          export FORUM_USERNAME=${{ matrix.name }}
          go run ./main.go
          if [ $? -ne 0 ]; then
            exit $?
          fi
