name: 秋舸7924

on:
  schedule:
    - cron: '55 16 * * *'

jobs:
  hjd-user:
    name: 秋舸7924
    uses: ./.github/workflows/reusable-hjd-login.yaml
    with:
      forum_username: 秋舸7924
      user_index: '12'
    secrets: inherit