name: 枍昉2751

on:
  schedule:
    - cron: '33 16 * * *'

jobs:
  hjd-user:
    name: 枍昉2751
    uses: ./.github/workflows/reusable-hjd-login.yaml
    with:
      forum_username: 枍昉2751
      user_index: '18'
    secrets: inherit