name: Daily Job
on:
  schedule:
    # Run this workflow "At xx:30 UTC every day"
    - cron: '30 16,17 * * *'
  push:

jobs:
  daily-hjd:
    name: daily hjd
    runs-on: ubuntu-22.04
    steps:
      - name: install chromium
        run: |
          sudo apt-get update
          sudo apt-get install -y chromium-browser
          sudo snap install chromium
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: hjd
          fetch-depth: 0
      - name: Run auto login
        env:
          FORUM_USERNAME: ${{ secrets.FORUM_USERNAME }}
          FORUM_PASSWORD: ${{ secrets.FORUM_PASSWORD }}
          SECURITY_QUESTION: ${{ secrets.SECURITY_QUESTION }}
          SECURITY_ANSWER: ${{ secrets.SECURITY_ANSWER }}
          CHROME_PATH: ${{ secrets.CHROME_PATH }}
        run: |
          go run ./main.go
