name: 砚迟1854

on:
  schedule: []

jobs:
  hjd-user:
    name: 砚迟1854
    uses: ./.github/workflows/reusable-hjd-login.yaml
    with:
      forum_username: 砚迟1854
      user_index: '2'
    secrets: inherit